-- AlterTable
ALTER TABLE "WardrobeItem" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "WardrobeItem" ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "WardrobeItem" ADD COLUMN IF NOT EXISTS "source" TEXT;
